GET http://localhost:5278/product/

###
GET http://localhost:5278/product/1

###
POST http://localhost:5278/product/
Content-Type: application/json

{
    "name": "House of Leaves",
    "initialStock": 20,
    "price": 15.99,
    "productType": 2
}

###

DELETE http://localhost:5278/product/2
