GET http://localhost:5278/product/

###

POST http://localhost:5278/product/
Content-Type: application/json

{
    "name": "House of Leaves",
    "initialStock": 20,
    "price": 15.99,
    "productType": 2
}